//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: meta.lib.proto.fbe
// FBE version: 1.14.2.0
//------------------------------------------------------------------------------

#pragma once

#if defined(__clang__)
#pragma clang system_header
#elif defined(__GNUC__)
#pragma GCC system_header
#elif defined(_MSC_VER)
#pragma system_header
#endif

#include "fbe_protocol.h"

#include "proto_models.h"

namespace FBE {

namespace proto {

// Fast Binary Encoding proto protocol version
struct ProtocolVersion
{
    // Protocol major version
    static const int major = 1;
    // Protocol minor version
    static const int minor = 0;
};

// Fast Binary Encoding proto sender
class Sender : public virtual FBE::Sender
{
public:
    Sender()
        : MetaMessageModel(this->_buffer)
        , MetaBinaryMessageModel(this->_buffer)
        , LiDARMapperMessageModel(this->_buffer)
    {}
    Sender(const Sender&) = delete;
    Sender(Sender&&) noexcept = delete;
    virtual ~Sender() = default;

    Sender& operator=(const Sender&) = delete;
    Sender& operator=(Sender&&) noexcept = delete;

    size_t send(const ::proto::MetaMessage& value);
    size_t send(const ::proto::MetaBinaryMessage& value);
    size_t send(const ::proto::LiDARMapperMessage& value);

public:
    // Sender models accessors
    FBE::proto::MetaMessageModel MetaMessageModel;
    FBE::proto::MetaBinaryMessageModel MetaBinaryMessageModel;
    FBE::proto::LiDARMapperMessageModel LiDARMapperMessageModel;
};

// Fast Binary Encoding proto receiver
class Receiver : public virtual FBE::Receiver
{
public:
    Receiver() {}
    Receiver(const Receiver&) = delete;
    Receiver(Receiver&&) = delete;
    virtual ~Receiver() = default;

    Receiver& operator=(const Receiver&) = delete;
    Receiver& operator=(Receiver&&) = delete;

protected:
    // Receive handlers
    virtual void onReceive(const ::proto::MetaMessage& value) {}
    virtual void onReceive(const ::proto::MetaBinaryMessage& value) {}
    virtual void onReceive(const ::proto::LiDARMapperMessage& value) {}

    // Receive message handler
    bool onReceive(size_t type, const void* data, size_t size) override;

private:
    // Receiver values accessors
    ::proto::MetaMessage MetaMessageValue;
    ::proto::MetaBinaryMessage MetaBinaryMessageValue;
    ::proto::LiDARMapperMessage LiDARMapperMessageValue;

    // Receiver models accessors
    FBE::proto::MetaMessageModel MetaMessageModel;
    FBE::proto::MetaBinaryMessageModel MetaBinaryMessageModel;
    FBE::proto::LiDARMapperMessageModel LiDARMapperMessageModel;
};

// Fast Binary Encoding proto proxy
class Proxy : public virtual FBE::Receiver
{
public:
    Proxy() {}
    Proxy(const Proxy&) = delete;
    Proxy(Proxy&&) = delete;
    virtual ~Proxy() = default;

    Proxy& operator=(const Proxy&) = delete;
    Proxy& operator=(Proxy&&) = delete;

protected:
    // Proxy handlers
    virtual void onProxy(FBE::proto::MetaMessageModel& model, size_t type, const void* data, size_t size) {}
    virtual void onProxy(FBE::proto::MetaBinaryMessageModel& model, size_t type, const void* data, size_t size) {}
    virtual void onProxy(FBE::proto::LiDARMapperMessageModel& model, size_t type, const void* data, size_t size) {}

    // Receive message handler
    bool onReceive(size_t type, const void* data, size_t size) override;

private:
    // Proxy models accessors
    FBE::proto::MetaMessageModel MetaMessageModel;
    FBE::proto::MetaBinaryMessageModel MetaBinaryMessageModel;
    FBE::proto::LiDARMapperMessageModel LiDARMapperMessageModel;
};

// Fast Binary Encoding proto client
class Client : public virtual Sender, protected virtual Receiver
{
public:
    Client() = default;
    Client(const Client&) = delete;
    Client(Client&&) = delete;
    virtual ~Client() = default;

    Client& operator=(const Client&) = delete;
    Client& operator=(Client&&) = delete;

    // Reset client buffers
    void reset() { std::scoped_lock locker(this->_lock); reset_requests(); }

    // Watchdog for timeouts
    void watchdog(uint64_t utc) { std::scoped_lock locker(this->_lock); watchdog_requests(utc); }


protected:
    std::mutex _lock;
    uint64_t _timestamp{0};

    virtual bool onReceiveResponse(const ::proto::MetaMessage& response) { return false; }
    virtual bool onReceiveResponse(const ::proto::MetaBinaryMessage& response) { return false; }
    virtual bool onReceiveResponse(const ::proto::LiDARMapperMessage& response) { return false; }

    virtual bool onReceiveReject(const ::proto::MetaMessage& reject) { return false; }
    virtual bool onReceiveReject(const ::proto::MetaBinaryMessage& reject) { return false; }
    virtual bool onReceiveReject(const ::proto::LiDARMapperMessage& reject) { return false; }

    virtual void onReceiveNotify(const ::proto::MetaMessage& notify) {}
    virtual void onReceiveNotify(const ::proto::MetaBinaryMessage& notify) {}
    virtual void onReceiveNotify(const ::proto::LiDARMapperMessage& notify) {}

    virtual void onReceive(const ::proto::MetaMessage& value) override { if (!onReceiveResponse(value) && !onReceiveReject(value)) onReceiveNotify(value); }
    virtual void onReceive(const ::proto::MetaBinaryMessage& value) override { if (!onReceiveResponse(value) && !onReceiveReject(value)) onReceiveNotify(value); }
    virtual void onReceive(const ::proto::LiDARMapperMessage& value) override { if (!onReceiveResponse(value) && !onReceiveReject(value)) onReceiveNotify(value); }

    // Reset client requests
    virtual void reset_requests();

    // Watchdog client requests for timeouts
    virtual void watchdog_requests(uint64_t utc);
};

} // namespace proto

} // namespace FBE
